### ISSUE TITLE
Namespace URI is not a URI

### ISSUE THREAD

**Issue by georghinkel** [bluezio/ttc2016-live#4]
I just noticed that the namespace URI for the families metamodel (and for the Persons metamodel as well) is set incorrectly: It is set to Families, which is not a valid URI. I am not sure that I can load models like this, so I would appreciate if you could add a valid URI for all metamodels. I know EMF is very tolerant on this, but NMF isn't, because it relies on the URI functionality of .NET which is more strict (though I would rather say it simply does its job).

A valid URI consists at least of a scheme, so example://Familes would be totally sufficient. However, this has to be done both in the metamodels and in the models.

**Comment by agarciadom** [comment]
Sorry, I didn't realize NMF would have issues with this. I've revised all the metamodels for the examples, the input and output models and the EMG launch configurations. Feel free to report back :-).
